alias lal="ls -alF"
alias ll='ls -l'
alias server="python -m SimpleHTTPServer"
alias pj='python -m json.tool'
alias p="cd ~/projects"

alias vssh='vagrant ssh'
alias vst='vagrant status'
alias vgst='vagrant global-status'
alias vup='vagrant up'
alias vhalt='vagrant halt'
alias vreload='vagrant reload'
alias vprov='vagrant provision'
alias vdestroy='vagrant destroy --force'
alias vbox='vagrant box'

alias dk='docker '
alias dkc='dk ps'
alias dkm='dk images'
alias dki='dk inspect'
alias dkb='dk build'
alias cleandkc="dkc -a --no-trunc| grep 'Exit' | awk '{print \$1}' | xargs -L 1 -r docker rm"
alias cleandkm="dkm -a --no-trunc | grep none | awk '{print \$3}' | xargs -L 1 -r docker rmi"
alias cleandk="cleandkc && cleandkm"
alias killdk='dk rm -f $(docker ps -qa)'

alias sd='sudo systemctl'
alias sdl='sd list-units'
alias sdcat='sd cat'

alias cci='sudo coreos-cloudinit --from-file'
alias j='journalctl'
alias e='etcdctl'
alias els='e ls --recursive'
alias eget='e get'
alias eset='e set'

alias f='fleetctl -strict-host-key-checking=false'
alias fss='f status'
alias fcat='f cat'
alias fstart='f start'
alias fld='f load'
alias fdry='f destroy'
alias flm='f list-machines'
alias flu='f list-units'
alias fsh='f ssh'

alias k='kubectl'
alias kget='kubectl get'
alias kdesc='kubectl describe'
alias kinfo='kubectl cluster-info'

function nsa { sudo nsenter -p -u -m -i -n -t $(docker inspect -f '{{ .State.Pid }}' $1) sh ; }
function sdrit() { sudo docker run -i -t $1 bash ; }
function dkip() { docker inspect --format '{{ .NetworkSettings.IPAddress }}' $1 ; }
